/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OChamadoRouteImport } from './routes/o-chamado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CultosRouteImport } from './routes/cultos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OChamadoRoute = OChamadoRouteImport.update({
  id: '/o-chamado',
  path: '/o-chamado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CultosRoute = CultosRouteImport.update({
  id: '/cultos',
  path: '/cultos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cultos': typeof CultosRoute
  '/login': typeof LoginRoute
  '/o-chamado': typeof OChamadoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registro': typeof RegistroRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cultos': typeof CultosRoute
  '/login': typeof LoginRoute
  '/o-chamado': typeof OChamadoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registro': typeof RegistroRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cultos': typeof CultosRoute
  '/login': typeof LoginRoute
  '/o-chamado': typeof OChamadoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/registro': typeof RegistroRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cultos'
    | '/login'
    | '/o-chamado'
    | '/perfil'
    | '/recuperar-senha'
    | '/registro'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cultos'
    | '/login'
    | '/o-chamado'
    | '/perfil'
    | '/recuperar-senha'
    | '/registro'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cultos'
    | '/login'
    | '/o-chamado'
    | '/perfil'
    | '/recuperar-senha'
    | '/registro'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CultosRoute: typeof CultosRoute
  LoginRoute: typeof LoginRoute
  OChamadoRoute: typeof OChamadoRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RegistroRoute: typeof RegistroRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-chamado': {
      id: '/o-chamado'
      path: '/o-chamado'
      fullPath: '/o-chamado'
      preLoaderRoute: typeof OChamadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultos': {
      id: '/cultos'
      path: '/cultos'
      fullPath: '/cultos'
      preLoaderRoute: typeof CultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CultosRoute: CultosRoute,
  LoginRoute: LoginRoute,
  OChamadoRoute: OChamadoRoute,
  PerfilRoute: PerfilRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RegistroRoute: RegistroRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
